/*
 * This file is generated by jOOQ.
 */
package kotlin_spring.models.tables.pojos


import com.fasterxml.jackson.annotation.JsonAutoDetect
import java.io.Serializable
import java.time.LocalDateTime


/**
 * This class is generated by jOOQ.
 */
@JsonAutoDetect(fieldVisibility = JsonAutoDetect.Visibility.ANY)
@Suppress("UNCHECKED_CAST")
data class TbUsers(
    var userId: Int? = null, 
    var userName: String? = null, 
    var userBirthdate: LocalDateTime? = null, 
    var userCpf: String? = null, 
    var userEmail: String? = null, 
    var userPhone: String? = null, 
    var userRole: String? = null, 
    var userPassword: String? = null
): Serializable {


    override fun toString(): String {
        val sb = StringBuilder("TbUsers (")

        sb.append(userId)
        sb.append(", ").append(userName)
        sb.append(", ").append(userBirthdate)
        sb.append(", ").append(userCpf)
        sb.append(", ").append(userEmail)
        sb.append(", ").append(userPhone)
        sb.append(", ").append(userRole)
        sb.append(", ").append(userPassword)

        sb.append(")")
        return sb.toString()
    }
}
