/*
 * This file is generated by jOOQ.
 */
package kotlin_spring.models.tables.references


import kotlin_spring.models.tables.TbUsers



/**
 * The table <code>public.tb_users</code>.
 */
val TB_USERS = TbUsers.TB_USERS
