/*
 * This file is generated by jOOQ.
 */
package kotlin_spring.models.keys


import kotlin_spring.models.tables.TbUsers
import kotlin_spring.models.tables.records.TbUsersRecord

import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal



// -------------------------------------------------------------------------
// UNIQUE and PRIMARY KEY definitions
// -------------------------------------------------------------------------

val TB_USERS_PKEY: UniqueKey<TbUsersRecord> = Internal.createUniqueKey(
    TbUsers.TB_USERS, DSL.name("tb_users_pkey"), arrayOf(
        TbUsers.TB_USERS.USER_ID), true)
val TB_USERS_USER_CPF_KEY: UniqueKey<TbUsersRecord> = Internal.createUniqueKey(
    TbUsers.TB_USERS, DSL.name("tb_users_user_cpf_key"), arrayOf(
        TbUsers.TB_USERS.USER_CPF), true)
val TB_USERS_USER_EMAIL_KEY: UniqueKey<TbUsersRecord> = Internal.createUniqueKey(
    TbUsers.TB_USERS, DSL.name("tb_users_user_email_key"), arrayOf(
        TbUsers.TB_USERS.USER_EMAIL), true)
val TB_USERS_USER_PHONE_KEY: UniqueKey<TbUsersRecord> = Internal.createUniqueKey(
    TbUsers.TB_USERS, DSL.name("tb_users_user_phone_key"), arrayOf(
        TbUsers.TB_USERS.USER_PHONE), true)
